// <auto-generated />
namespace TimeTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedDateTimeType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedDateTimeType));
        
        string IMigrationMetadata.Id
        {
            get { return "202212272038431_changedDateTimeType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
