// <auto-generated />
namespace TimeTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedMultipleRecorderPerTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedMultipleRecorderPerTask));
        
        string IMigrationMetadata.Id
        {
            get { return "202301031219315_changedMultipleRecorderPerTask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
